const students = [
    {
      name: "Alice Johnson",
      dob: "2000-05-14",
      gender: "Female",
      contact: "9876543210",
      altContact: "9123456780",
      email: "alice@example.com",
      altEmail: "alice.alt@example.com",
      collegeEmail: "alice@college.edu",
      regNo: "REG001",
      batch: "2021",
      tenth: "92%",
      twelfth: "89%",
      UG: "8.6 CGPA",
      PG: "NA",
      gap: "0",
      lans: "Java, Python",
      domain: "Web Development",
      resume: "https://example.com/resume/alice",
      role: "Frontend Developer"
    },
    {
      name: "Bob Smith",
      dob: "1999-08-23",
      gender: "Male",
      contact: "9871234560",
      altContact: "9023456712",
      email: "bob@example.com",
      altEmail: "bob.alt@example.com",
      collegeEmail: "bob@college.edu",
      regNo: "REG002",
      batch: "2020",
      tenth: "85%",
      twelfth: "90%",
      UG: "8.2 CGPA",
      PG: "7.8 CGPA",
      gap: "1",
      lans: "C++, JavaScript",
      domain: "Backend Development",
      resume: "https://example.com/resume/bob",
      role: "Backend Developer"
    },
    {
      name: "Clara Lee",
      dob: "2001-01-10",
      gender: "Female",
      contact: "9988776655",
      altContact: "9112233445",
      email: "clara@example.com",
      altEmail: "clara.alt@example.com",
      collegeEmail: "clara@college.edu",
      regNo: "REG003",
      batch: "2022",
      tenth: "91%",
      twelfth: "93%",
      UG: "8.9 CGPA",
      PG: "NA",
      gap: "0",
      lans: "Python, SQL",
      domain: "Data Science",
      resume: "https://example.com/resume/clara",
      role: "Data Analyst"
    },
    {
      name: "David Miller",
      dob: "1998-12-05",
      gender: "Male",
      contact: "9090909090",
      altContact: "9009009001",
      email: "david@example.com",
      altEmail: "david.alt@example.com",
      collegeEmail: "david@college.edu",
      regNo: "REG004",
      batch: "2019",
      tenth: "87%",
      twelfth: "86%",
      UG: "7.5 CGPA",
      PG: "8.0 CGPA",
      gap: "2",
      lans: "C, Java",
      domain: "AI/ML",
      resume: "https://example.com/resume/david",
      role: "Machine Learning Engineer"
    },
    {
      name: "Emily Carter",
      dob: "2000-07-22",
      gender: "Female",
      contact: "8888777766",
      altContact: "9333444555",
      email: "emily@example.com",
      altEmail: "emily.alt@example.com",
      collegeEmail: "emily@college.edu",
      regNo: "REG005",
      batch: "2021",
      tenth: "93%",
      twelfth: "94%",
      UG: "9.0 CGPA",
      PG: "NA",
      gap: "0",
      lans: "HTML, CSS, JavaScript",
      domain: "UI/UX",
      resume: "https://example.com/resume/emily",
      role: "UI Designer"
    },
    {
      name: "Franklin Scott",
      dob: "1997-11-18",
      gender: "Male",
      contact: "7777666655",
      altContact: "9001122334",
      email: "frank@example.com",
      altEmail: "frank.alt@example.com",
      collegeEmail: "frank@college.edu",
      regNo: "REG006",
      batch: "2018",
      tenth: "88%",
      twelfth: "82%",
      UG: "8.1 CGPA",
      PG: "8.3 CGPA",
      gap: "1",
      lans: "Python, Django",
      domain: "Web Development",
      resume: "https://example.com/resume/frank",
      role: "Full Stack Developer"
    },
    {
      name: "Grace Turner",
      dob: "2002-03-15",
      gender: "Female",
      contact: "8666554433",
      altContact: "9009988776",
      email: "grace@example.com",
      altEmail: "grace.alt@example.com",
      collegeEmail: "grace@college.edu",
      regNo: "REG007",
      batch: "2023",
      tenth: "95%",
      twelfth: "92%",
      UG: "9.2 CGPA",
      PG: "NA",
      gap: "0",
      lans: "JavaScript, React",
      domain: "Frontend Development",
      resume: "https://example.com/resume/grace",
      role: "React Developer"
    },
    {
      name: "Henry Watson",
      dob: "1996-06-30",
      gender: "Male",
      contact: "7555443322",
      altContact: "9556677889",
      email: "henry@example.com",
      altEmail: "henry.alt@example.com",
      collegeEmail: "henry@college.edu",
      regNo: "REG008",
      batch: "2017",
      tenth: "84%",
      twelfth: "86%",
      UG: "7.9 CGPA",
      PG: "8.4 CGPA",
      gap: "2",
      lans: "C#, .NET",
      domain: "Software Development",
      resume: "https://example.com/resume/henry",
      role: "Software Engineer"
    },
    {
      name: "Isla Brooks",
      dob: "2000-09-09",
      gender: "Female",
      contact: "9443322110",
      altContact: "9554433221",
      email: "isla@example.com",
      altEmail: "isla.alt@example.com",
      collegeEmail: "isla@college.edu",
      regNo: "REG009",
      batch: "2021",
      tenth: "89%",
      twelfth: "90%",
      UG: "8.5 CGPA",
      PG: "NA",
      gap: "0",
      lans: "Python, R",
      domain: "Data Science",
      resume: "https://example.com/resume/isla",
      role: "Data Scientist"
    },
    {
      name: "Jack Daniels",
      dob: "1999-04-01",
      gender: "Male",
      contact: "9332211009",
      altContact: "9445566778",
      email: "jack@example.com",
      altEmail: "jack.alt@example.com",
      collegeEmail: "jack@college.edu",
      regNo: "REG010",
      batch: "2020",
      tenth: "90%",
      twelfth: "88%",
      UG: "8.0 CGPA",
      PG: "8.1 CGPA",
      gap: "1",
      lans: "Go, Rust",
      domain: "System Programming",
      resume: "https://example.com/resume/jack",
      role: "System Developer"
    }
  ];

  export default students;
  